#!/usr/bin/env python3

import argparse
import logging

from scripts.fs import available_fs
from scripts.runner import Runner
from scripts.utils import add_common_args, parse_args

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("run")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build and run tests or benchmarks")
    parser.add_argument(
        "cmake_target",
        help="see .cpp files in `test` and `bench` for available targets",
    )
    parser.add_argument(
        "-c",
        "--cmake_args",
        default="",
        help="additional build arguments to be passed to CMake",
    )
    parser.add_argument(
        "-f",
        "--fs",
        default="uLayFS",
        choices=available_fs.keys(),
        help="filesystem type to be used",
    )
    add_common_args(parser)
    args = parse_args(parser)
    if args.build_type is None:
        args.build_type = "debug" if args.cmake_target.startswith("test") else "release"
    logger.info(f"args={args}")

    runner = Runner(name=args.cmake_target, build_type=args.build_type)
    runner.build(cmake_args=args.cmake_args)
    runner.run(
        additional_args=args.additional_args,
        fs=args.fs,
        trace=args.trace,
    )
