#!/usr/bin/env python3

import argparse
import logging
import sys

from utils import init

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("init")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--install_build_deps", action="store_true")
    parser.add_argument("--install_dev_deps", action="store_true")
    parser.add_argument("--configure", action="store_true")
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit()
    args = parser.parse_args()
    logger.info(f"args={args}")
    init(**vars(args))
