name: Benchmark

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "build type to use for the benchmark"
        required: true
        default: "release"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bench_append
        run: ./run bench_append ${{matrix.build_type}}
